# Generated by Django 5.0.2 on 2026-03-05 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'transaction_items',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale (বিক্রয়)'), ('purchase', 'Purchase (ক্রয়)'), ('expense', 'Expense (খরচ)'), ('income', 'Income (আয়)'), ('payment_in', 'Received (টাকা পেলাম)'), ('payment_out', 'Paid (টাকা দিলাম)'), ('return_in', 'Return Received (ফেরত পেলাম)'), ('return_out', 'Return Given (ফেরত দিলাম)')], db_index=True, max_length=20)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash (নগদ)'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank (ব্যাংক)'), ('credit', 'Credit (বাকি)'), ('other', 'Other (অন্যান্য)')], default='cash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('expense_category', models.CharField(blank=True, choices=[('employee', 'Employee Salary (কর্মচারী বেতন)'), ('electricity', 'Electricity Bill (বিদ্যুৎ বিল)'), ('rent', 'Shop Rent (দোকান ভাড়া)'), ('transport', 'Transport (পরিবহন)'), ('others', 'Others (অন্যান্য)')], default='', help_text='Expense category (কর্মচারী, বিদ্যুৎ, ভাড়া, পরিবহন, অন্যান্য)', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='transactions/')),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='contacts.contact')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
