# Generated by Django 5.0.2 on 2026-03-05 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantWallet',
            fields=[
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bkash_number', models.CharField(blank=True, max_length=15)),
                ('nagad_number', models.CharField(blank=True, max_length=15)),
                ('rocket_number', models.CharField(blank=True, max_length=15)),
                ('merchant_qr_id', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'merchant_wallets',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='BDT', max_length=5)),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('sender_number', models.CharField(blank=True, max_length=20)),
                ('receiver_number', models.CharField(blank=True, max_length=20)),
                ('qr_code_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending (অপেক্ষমান)'), ('success', 'Success (সফল)'), ('failed', 'Failed (ব্যর্থ)'), ('cancelled', 'Cancelled (বাতিল)'), ('refunded', 'Refunded (ফেরত)')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('webhook_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to='transactions.transaction')),
            ],
            options={
                'db_table': 'payment_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'status'], name='payment_log_merchan_ccbf67_idx'), models.Index(fields=['gateway', 'gateway_transaction_id'], name='payment_log_gateway_196ffd_idx')],
            },
        ),
    ]
