# Generated by Django 5.0.2 on 2026-03-05 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['merchant', 'contact_type'], name='contacts_merchan_de549c_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['merchant', 'is_active'], name='contacts_merchan_44ac81_idx'),
        ),
    ]
