# Generated by Django 5.0.2 on 2026-03-05 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['merchant', 'category'], name='products_merchan_d2c683_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['merchant', 'is_active'], name='products_merchan_9253e4_idx'),
        ),
    ]
